export {default as Ellipse} from './auth/Ellipse.svg'
export {default as Lady} from './auth/lady.svg'
export {default as Gent} from './auth/gent.svg'
export {default as BackArrow} from './auth/back.svg'
export {default as LogoIcon} from './auth/logo.svg'
export {default as EyeVisible} from './auth/eye-visible.svg'
export {default as EyeInvisible} from './auth/eye-invisible.svg'